import { Facility, Booking } from '@/features/facilities/types/facility.types';
import { Visitor } from '@/features/visitors/types/visitor.types';
import { Announcement } from '@/features/announcements/types/announcement.types';

export const INITIAL_FACILITIES: Facility[] = [
  {
    id: 1,
    name: 'Grand Clubhouse & Banquet Hall',
    type: 'Event Space',
    capacity: 120,
    location: 'Central Plaza, Ground Level',
    operatingHoursStart: '08:00:00',
    operatingHoursEnd: '23:00:00',
    status: 'ACTIVE',
  },
  {
    id: 2,
    name: 'Olympic Swimming Pool & Sundeck',
    type: 'Recreation',
    capacity: 40,
    location: 'East Wing Courtyard',
    operatingHoursStart: '06:00:00',
    operatingHoursEnd: '21:00:00',
    status: 'ACTIVE',
  },
  {
    id: 3,
    name: 'Rooftop Tennis Court',
    type: 'Sports',
    capacity: 4,
    location: 'Tower A, Level 18',
    operatingHoursStart: '07:00:00',
    operatingHoursEnd: '20:00:00',
    status: 'ACTIVE',
  },
  {
    id: 4,
    name: 'Skyline Residents Lounge & Library',
    type: 'Coworking & Study',
    capacity: 25,
    location: 'Tower B, Level 15',
    operatingHoursStart: '07:00:00',
    operatingHoursEnd: '23:00:00',
    status: 'ACTIVE',
  },
  {
    id: 5,
    name: 'Fitness & Cardio Center',
    type: 'Gymnasium',
    capacity: 30,
    location: 'West Wing, Level 2',
    operatingHoursStart: '05:30:00',
    operatingHoursEnd: '22:30:00',
    status: 'ACTIVE',
  },
  {
    id: 6,
    name: 'Barbecue Pavilion & Garden',
    type: 'Outdoor Dining',
    capacity: 20,
    location: 'North Garden Lawn',
    operatingHoursStart: '10:00:00',
    operatingHoursEnd: '22:00:00',
    status: 'INACTIVE', // Maintenance example
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 1,
    facilityId: 1,
    facilityName: 'Grand Clubhouse & Banquet Hall',
    requesterId: 'resident-001',
    requesterName: 'Sarah Jenkins',
    unitId: 'Tower A - 402',
    requesterRole: 'RESIDENT',
    startTime: '2026-09-25T18:00:00',
    endTime: '2026-09-25T21:00:00',
    status: 'APPROVED',
    attendeeCount: 45,
    purpose: 'Annual Residents Evening Gala',
    createdAt: '2026-09-24T10:15:00',
  },
  {
    id: 2,
    facilityId: 2,
    facilityName: 'Olympic Swimming Pool & Sundeck',
    requesterId: 'resident-002',
    requesterName: 'Michael Chen',
    unitId: 'Tower B - 205',
    requesterRole: 'RESIDENT',
    startTime: '2026-09-26T09:00:00',
    endTime: '2026-09-26T11:00:00',
    status: 'PENDING',
    attendeeCount: 12,
    purpose: 'Youth Swimming Training Meet',
    createdAt: '2026-09-24T11:30:00',
  },
  {
    id: 3,
    facilityId: 3,
    facilityName: 'Rooftop Tennis Court',
    requesterId: 'resident-001',
    requesterName: 'Sarah Jenkins',
    unitId: 'Tower A - 402',
    requesterRole: 'RESIDENT',
    startTime: '2026-09-27T08:00:00',
    endTime: '2026-09-27T09:30:00',
    status: 'APPROVED',
    attendeeCount: 4,
    purpose: 'Weekend Doubles Tennis Practice',
    createdAt: '2026-09-23T15:20:00',
  },
  {
    id: 4,
    facilityId: 4,
    facilityName: 'Skyline Residents Lounge & Library',
    requesterId: 'resident-002',
    requesterName: 'Michael Chen',
    unitId: 'Tower B - 205',
    requesterRole: 'RESIDENT',
    startTime: '2026-09-28T14:00:00',
    endTime: '2026-09-28T16:00:00',
    status: 'PENDING',
    attendeeCount: 8,
    purpose: 'Residents Tech & Book Study Group',
    createdAt: '2026-09-24T12:00:00',
  },
];

export const INITIAL_VISITORS: Visitor[] = [
  {
    id: 1,
    visitorName: 'Arthur Dent',
    residentId: 'resident-001',
    unitId: 'Tower A - 402',
    purpose: 'Family Visit & Dinner',
    visitDate: '2026-09-24',
    status: 'CHECKED_IN',
    checkedInAt: '2026-09-24T14:30:00',
    createdAt: '2026-09-23T09:00:00',
  },
  {
    id: 2,
    visitorName: 'Dr. Rebecca Chambers',
    residentId: 'resident-001',
    unitId: 'Tower A - 402',
    purpose: 'Consultation & Delivery',
    visitDate: '2026-09-25',
    status: 'EXPECTED',
    checkedInAt: null,
    createdAt: '2026-09-24T10:00:00',
  },
  {
    id: 3,
    visitorName: 'Marcus Holloway',
    residentId: 'resident-002',
    unitId: 'Tower B - 205',
    purpose: 'Fiber Internet Technician',
    visitDate: '2026-09-25',
    status: 'EXPECTED',
    checkedInAt: null,
    createdAt: '2026-09-24T11:20:00',
  },
  {
    id: 4,
    visitorName: 'Elena Rostova',
    residentId: 'resident-002',
    unitId: 'Tower B - 205',
    purpose: 'Guest Stay',
    visitDate: '2026-09-26',
    status: 'EXPECTED',
    checkedInAt: null,
    createdAt: '2026-09-24T12:45:00',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 1,
    title: 'Quarterly Fire Alarm & Safety Drill',
    content: 'Please be informed that the annual safety inspection and smoke alarm verification will occur this Saturday between 10:00 AM and 1:00 PM. Elevators will operate normally except for a brief 10-minute test period.',
    targetRole: 'ALL',
    publishedBy: 'Building Management Office',
    status: 'ACTIVE',
    createdAt: '2026-09-23T08:30:00',
  },
  {
    id: 2,
    title: 'Swimming Pool Maintenance Notice',
    content: 'The Olympic Swimming Pool will undergo deep chemical cleaning and filtration maintenance on Monday morning from 06:00 to 11:00. The sundeck will remain open.',
    targetRole: 'RESIDENT',
    publishedBy: 'Facilities Supervisor',
    status: 'ACTIVE',
    createdAt: '2026-09-24T09:00:00',
  },
  {
    id: 3,
    title: 'Security Protocol: QR Visitor Gate Passes',
    content: 'Security staff are reminded to verify all visitor identification and match pre-registered visitor QR logs before granting barrier access.',
    targetRole: 'STAFF',
    publishedBy: 'Chief Security Officer',
    status: 'ACTIVE',
    createdAt: '2026-09-22T14:10:00',
  },
  {
    id: 4,
    title: 'Annual General Assembly for Property Owners',
    content: 'Annual AGM scheduled for October 15 in the Grand Clubhouse. Agenda includes capital reserve allocation and solar panel roof installation proposal.',
    targetRole: 'OWNER',
    publishedBy: 'Executive Committee',
    status: 'ACTIVE',
    createdAt: '2026-09-20T16:00:00',
  },
];
